# This is a basic workflow to help you get started with Actions

name: mixpix3ls's workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Use the Node.js Action
      - name: Use Node.js
        uses: actions/setup-node@v1
      # Install npm using the Node.js Action
      - name: Install npm
        run: npm install
      # Run gulp
      - name: Execute gulp
        run: gulp build

      # Upload artifact
      - name: Run a multi-line script
        uses: actions/upload-artifact@vi
        with:
          name: book-github-actions-package
          path: dest
